package KLTN.RAG_CHATBOT_BE.rag.retrieve;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration-style tests for query-variant dedupe behavior in the retrieval pipeline.
 *
 * No live MySQL / Qdrant / Cohere API required.
 * Tests simulate the search-call pattern that {@link RagRetrievalService} executes
 * after dedupe, verifying call-count and recall properties.
 */
class QueryVariantDedupeIntegrationTest {

    private static final String WIDGET_ID = UUID.randomUUID().toString();
    private static final String MODE = "VECTOR";

    /** Simulate the Qdrant search call pattern after dedupe. */
    private int simulateQdrantCalls(List<String> variants, boolean dedupeEnabled) {
        QueryVariantDedupe.DedupeResult dedupeResult =
                QueryVariantDedupe.dedupe(variants, dedupeEnabled, WIDGET_ID, MODE);
        AtomicInteger calls = new AtomicInteger(0);
        for (QueryVariantDedupe.QueryVariant qv : dedupeResult.uniqueVariants()) {
            // Simulate one Qdrant call per unique variant
            calls.incrementAndGet();
        }
        return calls.get();
    }

    // ─────────────────────────────────────────────────────────────────
    // Test 1 — duplicate variants call Qdrant once
    // ─────────────────────────────────────────────────────────────────

    @Test
    void duplicateVariants_callQdrantOnce() {
        List<String> variants = List.of(
                "Kỹ năng mềm Nhóm 4",
                "kỹ năng   mềm nhóm 4",
                "kỹ năng mềm nhóm 4"
        );

        int callCount = simulateQdrantCalls(variants, true);

        assertEquals(1, callCount,
                "All three variants normalize identically; Qdrant should be called once");
    }

    @Test
    void representativeResultStillUsed_whenDuplicatesSkipped() {
        List<String> variants = List.of(
                "Kỹ năng mềm Nhóm 4",
                "kỹ năng mềm nhóm 4"
        );

        QueryVariantDedupe.DedupeResult result =
                QueryVariantDedupe.dedupe(variants, true, WIDGET_ID, MODE);

        assertEquals(1, result.unique());
        // The representative (first occurrence) is the unique variant
        assertEquals("Kỹ năng mềm Nhóm 4", result.uniqueVariants().get(0).originalText());
        // The second variant references the representative
        assertEquals("Kỹ năng mềm Nhóm 4", result.allVariants().get(1).representedBy());
    }

    // ─────────────────────────────────────────────────────────────────
    // Test 2 — distinct variants call Qdrant separately
    // ─────────────────────────────────────────────────────────────────

    @Test
    void distinctVariants_K46_vs_K45_callQdrantSeparately() {
        List<String> variants = List.of(
                "Kiến trúc K46 học kỳ 2",
                "Kiến trúc K45 học kỳ 2"
        );

        int callCount = simulateQdrantCalls(variants, true);

        assertEquals(2, callCount,
                "K46 and K45 must not be deduped — separate Qdrant calls required");
    }

    @Test
    void distinctVariants_Nhom4_vs_Nhom2_callQdrantSeparately() {
        List<String> variants = List.of(
                "Kỹ năng mềm Nhóm 4",
                "Kỹ năng mềm Nhóm 2"
        );

        int callCount = simulateQdrantCalls(variants, true);

        assertEquals(2, callCount,
                "Nhóm 4 and Nhóm 2 must not be deduped — separate Qdrant calls required");
    }

    // ─────────────────────────────────────────────────────────────────
    // Test 3 — old behavior preserved when dedupe disabled
    // ─────────────────────────────────────────────────────────────────

    @Test
    void dedupeDisabled_callsQdrantForEveryVariant() {
        List<String> variants = List.of(
                "Kỹ năng mềm Nhóm 4",
                "kỹ năng mềm nhóm 4",
                "kỹ năng   mềm nhóm 4"
        );

        int callCount = simulateQdrantCalls(variants, false);

        assertEquals(3, callCount,
                "When dedupe is disabled, every original variant must trigger a Qdrant call");
    }

    // ─────────────────────────────────────────────────────────────────
    // Test 4 — recall guard for exact schedule query
    // ─────────────────────────────────────────────────────────────────

    @Test
    void exactScheduleQuery_Nhom4_candidatePreserved() {
        // Variants generated by rewriteQuery() for a schedule query
        List<String> variants = List.of(
                "Kỹ năng mềm Nhóm 4 học với giảng viên nào, thứ mấy, tiết nào, phòng nào?",
                "Kỹ năng mềm Nhóm 4 học với giảng viên nào, thứ mấy, tiết nào, phòng nào",
                "Kỹ năng mềm Nhóm 4",
                "kỹ năng mềm nhóm 4 học với giảng viên nào, thứ mấy, tiết nào, phòng nào"
        );

        QueryVariantDedupe.DedupeResult result =
                QueryVariantDedupe.dedupe(variants, true, WIDGET_ID, MODE);

        // Verify no Nhóm 4 identifier is lost in the unique variants
        boolean nhom4Present = result.uniqueVariants().stream()
                .anyMatch(qv -> qv.originalText().toLowerCase().contains("nhóm 4")
                        || qv.originalText().toLowerCase().contains("nhom 4"));
        assertTrue(nhom4Present,
                "Nhóm 4 identifier must survive in at least one unique variant");

        // Verify distinct variants are kept (original with "?" vs normalized)
        assertTrue(result.unique() >= 1,
                "At least 1 unique variant must exist for a schedule query");
    }

    // ─────────────────────────────────────────────────────────────────
    // Test 5 — recall guard for curriculum list query
    // ─────────────────────────────────────────────────────────────────

    @Test
    void curriculumListQuery_K46_HK2_notMixedWithK45_HK1() {
        // Simulated variants for curriculum query — K46 HK2 must stay distinct from K45 HK1
        List<String> variants = List.of(
                "Ngành Kiến trúc K46 có những học phần nào ở học kỳ 2?",
                "Ngành Kiến trúc K46 có những học phần nào ở học kỳ 2",
                "Kiến trúc K46 học kỳ 2",
                "Ngành Kiến trúc K45 có những học phần nào ở học kỳ 1?"
        );

        QueryVariantDedupe.DedupeResult result =
                QueryVariantDedupe.dedupe(variants, true, WIDGET_ID, MODE);

        // K46 and K45 variants must NOT be deduped together
        boolean hasK46 = result.uniqueVariants().stream()
                .anyMatch(qv -> qv.originalText().contains("K46"));
        boolean hasK45 = result.uniqueVariants().stream()
                .anyMatch(qv -> qv.originalText().contains("K45"));

        assertTrue(hasK46, "K46 must be present in unique variants");
        assertTrue(hasK45, "K45 must be present in unique variants — must not be merged with K46");
    }

    @Test
    void curriculumListQuery_duplicateVariants_reducedCallCount() {
        // Simulate what rewriteQuery() might produce for a curriculum query:
        // original + stripped (no "?") + normalized lowercase — last two might normalize identically
        List<String> variants = List.of(
                "Ngành Kiến trúc K46 có những học phần nào ở học kỳ 2?",
                "Ngành Kiến trúc K46 có những học phần nào ở học kỳ 2",
                "ngành kiến trúc k46 có những học phần nào ở học kỳ 2"
        );

        QueryVariantDedupe.DedupeResult withDedupe =
                QueryVariantDedupe.dedupe(variants, true, WIDGET_ID, MODE);
        QueryVariantDedupe.DedupeResult withoutDedupe =
                QueryVariantDedupe.dedupe(variants, false, WIDGET_ID, MODE);

        // Dedupe should reduce calls when last two are identical after normalization
        assertTrue(withDedupe.unique() <= withoutDedupe.unique(),
                "Dedupe must not increase call count");
        // K46 must still be present
        boolean k46Present = withDedupe.uniqueVariants().stream()
                .anyMatch(qv -> qv.originalText().contains("K46"));
        assertTrue(k46Present, "K46 identifier must survive dedupe");
    }

    // ─────────────────────────────────────────────────────────────────
    // No-regression: empty / null variants
    // ─────────────────────────────────────────────────────────────────

    @Test
    void nullVariantList_handledGracefully() {
        QueryVariantDedupe.DedupeResult result =
                QueryVariantDedupe.dedupe(null, true, WIDGET_ID, MODE);

        assertEquals(0, result.total());
        assertEquals(0, result.unique());
        assertEquals(0, result.skipped());
    }
}
